# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Group')),
            ],
        ),
    ]
